AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs12.x
    Tracing: Active
    Timeout: 30

Resources:
  ReceivedTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: EmailReceivedTopic
      TopicName: EmailReceivedTopic

  ForwardEmail:
    Type: AWS::Serverless::Function
    Properties:
      Handler: forward.default
      CodeUri: ./dist/forwarder/forward
      Events:
        Notified:
          Type: SNS
          Properties:
            Topic: !Ref ReceivedTopic
